/*
 Flickity PACKAGED v2.0.5
 Touch, responsive, flickable carousels

 Licensed GPLv3 for open source use
 or Flickity Commercial License for commercial use

 http://flickity.metafizzy.co
 Copyright 2016 Metafizzy
 getSize v2.0.2
 measure size of elements
 MIT license
 Unipointer v2.1.0
 base class for doing one thing with pointer event
 MIT license
 Unidragger v2.1.0
 Draggable base class
 MIT license
 Tap listener v2.0.0
 listens to taps
 MIT license
 Flickity v2.0.5
 Touch, responsive, flickable carousels

 Licensed GPLv3 for open source use
 or Flickity Commercial License for commercial use

 http://flickity.metafizzy.co
 Copyright 2016 Metafizzy
 Flickity asNavFor v2.0.1
 enable asNavFor for Flickity
 imagesLoaded v4.1.1
 JavaScript is all like "You images are done yet or what?"
 MIT License
 Flickity imagesLoaded v2.0.0
 enables imagesLoaded option for Flickity
*/
(function(b,c){"function"==typeof define&&define.amd?define("jquery-bridget/jquery-bridget",["jquery"],function(f){return c(b,f)}):"object"==typeof module&&module.exports?module.exports=c(b,require("jquery")):b.jQueryBridget=c(b,b.jQuery)})(window,function(b,c){function f(e,f,l){function n(a,b,d){var c,t="$()."+e+'("'+b+'")';a.each(function(a,n){var f=l.data(n,e);if(f){var m=f[b];m&&"_"!=b.charAt(0)?(f=m.apply(f,d),c=void 0===c?f:c):g(t+" is not a valid method")}else g(e+" not initialized. Cannot call methods, i.e. "+
t)});return void 0!==c?c:a}function m(a,g){a.each(function(a,b){var d=l.data(b,e);d?(d.option(g),d._init()):(d=new f(b,g),l.data(b,e,d))})}if(l=l||c||b.jQuery)f.prototype.option||(f.prototype.option=function(a){l.isPlainObject(a)&&(this.options=l.extend(!0,this.options,a))}),l.fn[e]=function(g){if("string"==typeof g){var e=a.call(arguments,1);return n(this,g,e)}m(this,g);return this},d(l)}function d(a){!a||a&&a.bridget||(a.bridget=f)}var a=Array.prototype.slice,e=b.console,g="undefined"==typeof e?
function(){}:function(a){e.error(a)};d(c||b.jQuery);return f});
(function(b,c){"function"==typeof define&&define.amd?define("ev-emitter/ev-emitter",c):"object"==typeof module&&module.exports?module.exports=c():b.EvEmitter=c()})("undefined"!=typeof window?window:this,function(){function b(){}var c=b.prototype;c.on=function(b,d){if(b&&d){var a=this._events=this._events||{},a=a[b]=a[b]||[];-1==a.indexOf(d)&&a.push(d);return this}};c.once=function(b,d){if(b&&d){this.on(b,d);var a=this._onceEvents=this._onceEvents||{};(a[b]=a[b]||{})[d]=!0;return this}};c.off=function(b,
d){var a=this._events&&this._events[b];if(a&&a.length){var e=a.indexOf(d);-1!=e&&a.splice(e,1);return this}};c.emitEvent=function(b,d){var a=this._events&&this._events[b];if(a&&a.length){var e=0,g=a[e];d=d||[];for(var c=this._onceEvents&&this._onceEvents[b];g;){var f=c&&c[g];f&&(this.off(b,g),delete c[g]);g.apply(this,d);e+=f?0:1;g=a[e]}return this}};return b});
(function(b,c){"function"==typeof define&&define.amd?define("get-size/get-size",[],function(){return c()}):"object"==typeof module&&module.exports?module.exports=c():b.getSize=c()})(window,function(){function b(a){var g=parseFloat(a);return-1==a.indexOf("%")&&!isNaN(g)&&g}function c(){}function f(g){(g=getComputedStyle(g))||a("Style returned "+g+". Are you running this code in a hidden iframe on Firefox? See http://bit.ly/getsizebug1");return g}function d(a){if(!n){n=!0;var c=document.createElement("div");
c.style.width="200px";c.style.padding="1px 2px 3px 4px";c.style.borderStyle="solid";c.style.borderWidth="1px 2px 3px 4px";c.style.boxSizing="border-box";var m=document.body||document.documentElement;m.appendChild(c);var p=f(c);d.isBoxSizeOuter=k=200==b(p.width);m.removeChild(c)}"string"==typeof a&&(a=document.querySelector(a));if(a&&"object"==typeof a&&a.nodeType){m=f(a);if("none"==m.display){c={width:0,height:0,innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0};for(m=0;m<g;m++)c[e[m]]=0;return c}c=
{};c.width=a.offsetWidth;c.height=a.offsetHeight;a=c.isBorderBox="border-box"==m.boxSizing;for(p=0;p<g;p++){var q=e[p],h=parseFloat(m[q]);c[q]=isNaN(h)?0:h}var p=c.paddingLeft+c.paddingRight,q=c.paddingTop+c.paddingBottom,h=c.marginLeft+c.marginRight,l=c.marginTop+c.marginBottom,t=c.borderLeftWidth+c.borderRightWidth,u=c.borderTopWidth+c.borderBottomWidth;a=a&&k;var v=b(m.width);!1!==v&&(c.width=v+(a?0:p+t));m=b(m.height);!1!==m&&(c.height=m+(a?0:q+u));c.innerWidth=c.width-(p+t);c.innerHeight=c.height-
(q+u);c.outerWidth=c.width+h;c.outerHeight=c.height+l;return c}}var a="undefined"==typeof console?c:function(a){console.error(a)},e="paddingLeft paddingRight paddingTop paddingBottom marginLeft marginRight marginTop marginBottom borderLeftWidth borderRightWidth borderTopWidth borderBottomWidth".split(" "),g=e.length,n=!1,k;return d});
(function(b,c){"function"==typeof define&&define.amd?define("desandro-matches-selector/matches-selector",c):"object"==typeof module&&module.exports?module.exports=c():b.matchesSelector=c()})(window,function(){var b=function(){var b=Element.prototype;if(b.matches)return"matches";if(b.matchesSelector)return"matchesSelector";for(var f=["webkit","moz","ms","o"],d=0;d<f.length;d++){var a=f[d]+"MatchesSelector";if(b[a])return a}}();return function(c,f){return c[b](f)}});
(function(b,c){"function"==typeof define&&define.amd?define("fizzy-ui-utils/utils",["desandro-matches-selector/matches-selector"],function(f){return c(b,f)}):"object"==typeof module&&module.exports?module.exports=c(b,require("desandro-matches-selector")):b.fizzyUIUtils=c(b,b.matchesSelector)})(window,function(b,c){var f={extend:function(a,e){for(var g in e)a[g]=e[g];return a},modulo:function(a,e){return(a%e+e)%e},makeArray:function(a){var e=[];if(Array.isArray(a))e=a;else if(a&&"number"==typeof a.length)for(var g=
0;g<a.length;g++)e.push(a[g]);else e.push(a);return e},removeFrom:function(a,e){var g=a.indexOf(e);-1!=g&&a.splice(g,1)},getParent:function(a,e){for(;a!=document.body;)if(a=a.parentNode,c(a,e))return a},getQueryElement:function(a){return"string"==typeof a?document.querySelector(a):a},handleEvent:function(a){var e="on"+a.type;if(this[e])this[e](a)},filterFindElements:function(a,e){a=f.makeArray(a);var g=[];a.forEach(function(a){if(a instanceof HTMLElement)if(e){c(a,e)&&g.push(a);a=a.querySelectorAll(e);
for(var b=0;b<a.length;b++)g.push(a[b])}else g.push(a)});return g},debounceMethod:function(a,e,g){var b=a.prototype[e],c=e+"Timeout";a.prototype[e]=function(){var a=this[c];a&&clearTimeout(a);var e=arguments,d=this;this[c]=setTimeout(function(){b.apply(d,e);delete d[c]},g||100)}},docReady:function(a){var e=document.readyState;"complete"==e||"interactive"==e?setTimeout(a):document.addEventListener("DOMContentLoaded",a)},toDashed:function(a){return a.replace(/(.)([A-Z])/g,function(a,g,b){return g+"-"+
b}).toLowerCase()}},d=b.console;f.htmlInit=function(a,e){f.docReady(function(){var g=f.toDashed(e),c="data-"+g,k=document.querySelectorAll("["+c+"]"),g=document.querySelectorAll(".js-"+g),k=f.makeArray(k).concat(f.makeArray(g)),l=c+"-options",r=b.jQuery;k.forEach(function(g){var b=g.getAttribute(c)||g.getAttribute(l),f;try{f=b&&JSON.parse(b)}catch(h){d&&d.error("Error parsing "+c+" on "+g.className+": "+h);return}b=new a(g,f);r&&r.data(g,e,b)})})};return f});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/cell",["get-size/get-size"],function(f){return c(b,f)}):"object"==typeof module&&module.exports?module.exports=c(b,require("get-size")):(b.Flickity=b.Flickity||{},b.Flickity.Cell=c(b,b.getSize))})(window,function(b,c){function f(a,b){this.element=a;this.parent=b;this.create()}var d=f.prototype;d.create=function(){this.element.style.position="absolute";this.shift=this.x=0};d.destroy=function(){this.element.style.position="";this.element.style[this.parent.originSide]=
""};d.getSize=function(){this.size=c(this.element)};d.setPosition=function(a){this.x=a;this.updateTarget();this.renderPosition(a)};d.updateTarget=d.setDefaultTarget=function(){this.target=this.x+this.size["left"==this.parent.originSide?"marginLeft":"marginRight"]+this.size.width*this.parent.cellAlign};d.renderPosition=function(a){this.element.style[this.parent.originSide]=this.parent.getPositionValue(a)};d.wrapShift=function(a){this.shift=a;this.renderPosition(this.x+this.parent.slideableWidth*a)};
d.remove=function(){this.element.parentNode.removeChild(this.element)};return f});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/slide",c):"object"==typeof module&&module.exports?module.exports=c():(b.Flickity=b.Flickity||{},b.Flickity.Slide=c())})(window,function(){function b(b){this.parent=b;this.isOriginLeft="left"==b.originSide;this.cells=[];this.height=this.outerWidth=0}var c=b.prototype;c.addCell=function(b){this.cells.push(b);this.outerWidth+=b.size.outerWidth;this.height=Math.max(b.size.outerHeight,this.height);1==this.cells.length&&(this.x=b.x,
this.firstMargin=b.size[this.isOriginLeft?"marginLeft":"marginRight"])};c.updateTarget=function(){var b=this.isOriginLeft?"marginRight":"marginLeft",c=this.getLastCell();this.target=this.x+this.firstMargin+(this.outerWidth-(this.firstMargin+(c?c.size[b]:0)))*this.parent.cellAlign};c.getLastCell=function(){return this.cells[this.cells.length-1]};c.select=function(){this.changeSelectedClass("add")};c.unselect=function(){this.changeSelectedClass("remove")};c.changeSelectedClass=function(b){this.cells.forEach(function(c){c.element.classList[b]("is-selected")})};
c.getCellElements=function(){return this.cells.map(function(b){return b.element})};return b});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/animate",["fizzy-ui-utils/utils"],function(f){return c(b,f)}):"object"==typeof module&&module.exports?module.exports=c(b,require("fizzy-ui-utils")):(b.Flickity=b.Flickity||{},b.Flickity.animatePrototype=c(b,b.fizzyUIUtils))})(window,function(b,c){var f=b.requestAnimationFrame||b.webkitRequestAnimationFrame,d=0;f||(f=function(a){var b=(new Date).getTime(),g=Math.max(0,16-(b-d));a=setTimeout(a,g);d=b+g;return a});var a={startAnimation:function(){this.isAnimating||
(this.isAnimating=!0,this.restingFrames=0,this.animate())},animate:function(){this.applyDragForce();this.applySelectedAttraction();var a=this.x;this.integratePhysics();this.positionSlider();this.settle(a);if(this.isAnimating){var b=this;f(function(){b.animate()})}}},e="string"==typeof document.documentElement.style.transform?"transform":"WebkitTransform";a.positionSlider=function(){var a=this.x;this.options.wrapAround&&1<this.cells.length&&(a=c.modulo(a,this.slideableWidth),a-=this.slideableWidth,
this.shiftWrapCells(a));a+=this.cursorPosition;a=this.options.rightToLeft&&e?-a:a;a=this.getPositionValue(a);this.slider.style[e]=this.isAnimating?"translate3d("+a+",0,0)":"translateX("+a+")";if(a=this.slides[0])a=-this.x-a.target,this.dispatchEvent("scroll",null,[a/this.slidesWidth,a])};a.positionSliderAtSelected=function(){this.cells.length&&(this.x=-this.selectedSlide.target,this.positionSlider())};a.getPositionValue=function(a){return this.options.percentPosition?.01*Math.round(a/this.size.innerWidth*
1E4)+"%":Math.round(a)+"px"};a.settle=function(a){this.isPointerDown||Math.round(100*this.x)!=Math.round(100*a)||this.restingFrames++;2<this.restingFrames&&(this.isAnimating=!1,delete this.isFreeScrolling,this.positionSlider(),this.dispatchEvent("settle"))};a.shiftWrapCells=function(a){this._shiftCells(this.beforeShiftCells,this.cursorPosition+a,-1);this._shiftCells(this.afterShiftCells,this.size.innerWidth-(a+this.slideableWidth+this.cursorPosition),1)};a._shiftCells=function(a,b,e){for(var g=0;g<
a.length;g++){var c=a[g];c.wrapShift(0<b?e:0);b-=c.size.outerWidth}};a._unshiftCells=function(a){if(a&&a.length)for(var b=0;b<a.length;b++)a[b].wrapShift(0)};a.integratePhysics=function(){this.x+=this.velocity;this.velocity*=this.getFrictionFactor()};a.applyForce=function(a){this.velocity+=a};a.getFrictionFactor=function(){return 1-this.options[this.isFreeScrolling?"freeScrollFriction":"friction"]};a.getRestingPosition=function(){return this.x+this.velocity/(1-this.getFrictionFactor())};a.applyDragForce=
function(){this.isPointerDown&&this.applyForce(this.dragX-this.x-this.velocity)};a.applySelectedAttraction=function(){this.isPointerDown||this.isFreeScrolling||!this.cells.length||this.applyForce((-1*this.selectedSlide.target-this.x)*this.options.selectedAttraction)};return a});
(function(b,c){if("function"==typeof define&&define.amd)define("flickity/js/flickity","ev-emitter/ev-emitter get-size/get-size fizzy-ui-utils/utils ./cell ./slide ./animate".split(" "),function(d,a,e,g,f,k){return c(b,d,a,e,g,f,k)});else if("object"==typeof module&&module.exports)module.exports=c(b,require("ev-emitter"),require("get-size"),require("fizzy-ui-utils"),require("./cell"),require("./slide"),require("./animate"));else{var f=b.Flickity;b.Flickity=c(b,b.EvEmitter,b.getSize,b.fizzyUIUtils,
f.Cell,f.Slide,f.animatePrototype)}})(window,function(b,c,f,d,a,e,g){function n(a,b){for(a=d.makeArray(a);a.length;)b.appendChild(a.shift())}function k(a,b){var e=d.getQueryElement(a);if(e){this.element=e;if(this.element.flickityGUID)return e=q[this.element.flickityGUID],e.option(b),e;l&&(this.$element=l(this.element));this.options=d.extend({},this.constructor.defaults);this.option(b);this._create()}else m&&m.error("Bad element for Flickity: "+(e||a))}var l=b.jQuery,r=b.getComputedStyle,m=b.console,
p=0,q={};k.defaults={accessibility:!0,cellAlign:"center",freeScrollFriction:.075,friction:.28,namespaceJQueryEvents:!0,percentPosition:!0,resize:!0,selectedAttraction:.025,setGallerySize:!0};k.createMethods=[];var h=k.prototype;d.extend(h,c.prototype);h._create=function(){var a=this.guid=++p;this.element.flickityGUID=a;q[a]=this;this.velocity=this.x=this.restingFrames=this.selectedIndex=0;this.originSide=this.options.rightToLeft?"right":"left";this.viewport=document.createElement("div");this.viewport.className=
"flickity-viewport";this._createSlider();(this.options.resize||this.options.watchCSS)&&b.addEventListener("resize",this);k.createMethods.forEach(function(a){this[a]()},this);this.options.watchCSS?this.watchCSS():this.activate()};h.option=function(a){d.extend(this.options,a)};h.activate=function(){if(!this.isActive){this.isActive=!0;this.element.classList.add("flickity-enabled");this.options.rightToLeft&&this.element.classList.add("flickity-rtl");this.getSize();var a=this._filterFindCellElements(this.element.children);
n(a,this.slider);this.viewport.appendChild(this.slider);this.element.appendChild(this.viewport);this.reloadCells();this.options.accessibility&&(this.element.tabIndex=0,this.element.addEventListener("keydown",this));this.emitEvent("activate");a=this.options.initialIndex;this.select(this.isInitActivated?this.selectedIndex:void 0!==a?this.cells[a]?a:0:0,!1,!0);this.isInitActivated=!0}};h._createSlider=function(){var a=document.createElement("div");a.className="flickity-slider";a.style[this.originSide]=
0;this.slider=a};h._filterFindCellElements=function(a){return d.filterFindElements(a,this.options.cellSelector)};h.reloadCells=function(){this.cells=this._makeCells(this.slider.children);this.positionCells();this._getWrapShiftCells();this.setGallerySize()};h._makeCells=function(b){return this._filterFindCellElements(b).map(function(b){return new a(b,this)},this)};h.getLastCell=function(){return this.cells[this.cells.length-1]};h.getLastSlide=function(){return this.slides[this.slides.length-1]};h.positionCells=
function(){this._sizeCells(this.cells);this._positionCells(0)};h._positionCells=function(a){this.maxCellHeight=(a=a||0)?this.maxCellHeight||0:0;var b=0;0<a&&(b=this.cells[a-1],b=b.x+b.size.outerWidth);for(var e=this.cells.length;a<e;a++){var g=this.cells[a];g.setPosition(b);b+=g.size.outerWidth;this.maxCellHeight=Math.max(g.size.outerHeight,this.maxCellHeight)}this.slideableWidth=b;this.updateSlides();this._containSlides();this.slidesWidth=e?this.getLastSlide().target-this.slides[0].target:0};h._sizeCells=
function(a){a.forEach(function(a){a.getSize()})};h.updateSlides=function(){this.slides=[];if(this.cells.length){var a=new e(this);this.slides.push(a);var b="left"==this.originSide?"marginRight":"marginLeft",g=this._getCanCellFit();this.cells.forEach(function(c,d){a.cells.length&&!g.call(this,d,a.outerWidth-a.firstMargin+(c.size.outerWidth-c.size[b]))&&(a.updateTarget(),a=new e(this),this.slides.push(a));a.addCell(c)},this);a.updateTarget();this.updateSelectedSlide()}};h._getCanCellFit=function(){var a=
this.options.groupCells;if(!a)return function(){return!1};if("number"==typeof a){var b=parseInt(a,10);return function(a){return 0!==a%b}}var e=(a="string"==typeof a&&a.match(/^(\d+)%$/))?parseInt(a[1],10)/100:1;return function(a,b){return b<=(this.size.innerWidth+1)*e}};h._init=h.reposition=function(){this.positionCells();this.positionSliderAtSelected()};h.getSize=function(){this.size=f(this.element);this.setCellAlign();this.cursorPosition=this.size.innerWidth*this.cellAlign};var w={center:{left:.5,
right:.5},left:{left:0,right:1},right:{right:0,left:1}};h.setCellAlign=function(){var a=w[this.options.cellAlign];this.cellAlign=a?a[this.originSide]:this.options.cellAlign};h.setGallerySize=function(){this.options.setGallerySize&&(this.viewport.style.height=(this.options.adaptiveHeight&&this.selectedSlide?this.selectedSlide.height:this.maxCellHeight)+"px")};h._getWrapShiftCells=function(){if(this.options.wrapAround){this._unshiftCells(this.beforeShiftCells);this._unshiftCells(this.afterShiftCells);
var a=this.cursorPosition;this.beforeShiftCells=this._getGapCells(a,this.cells.length-1,-1);a=this.size.innerWidth-this.cursorPosition;this.afterShiftCells=this._getGapCells(a,0,1)}};h._getGapCells=function(a,b,e){for(var g=[];0<a;){var c=this.cells[b];if(!c)break;g.push(c);b+=e;a-=c.size.outerWidth}return g};h._containSlides=function(){if(this.options.contain&&!this.options.wrapAround&&this.cells.length){var a=this.options.rightToLeft,b=a?"marginRight":"marginLeft",a=a?"marginLeft":"marginRight",
e=this.slideableWidth-this.getLastCell().size[a],g=e<this.size.innerWidth,c=this.cursorPosition+this.cells[0].size[b],d=e-this.size.innerWidth*(1-this.cellAlign);this.slides.forEach(function(a){g?a.target=e*this.cellAlign:(a.target=Math.max(a.target,c),a.target=Math.min(a.target,d))},this)}};h.dispatchEvent=function(a,b,e){var g=b?[b].concat(e):e;this.emitEvent(a,g);l&&this.$element&&(g=a+=this.options.namespaceJQueryEvents?".flickity":"",b&&(b=l.Event(b),b.type=a,g=b),this.$element.trigger(g,e))};
h.select=function(a,b,e){if(this.isActive){a=parseInt(a,10);this._wrapSelect(a);if(this.options.wrapAround||b)a=d.modulo(a,this.slides.length);this.slides[a]&&(this.selectedIndex=a,this.updateSelectedSlide(),e?this.positionSliderAtSelected():this.startAnimation(),this.options.adaptiveHeight&&this.setGallerySize(),this.dispatchEvent("select"),this.dispatchEvent("cellSelect"))}};h._wrapSelect=function(a){var b=this.slides.length;if(!(this.options.wrapAround&&1<b))return a;var e=d.modulo(a,b),g=Math.abs(e-
this.selectedIndex),c=Math.abs(e+b-this.selectedIndex),e=Math.abs(e-b-this.selectedIndex);!this.isDragSelect&&c<g?a+=b:!this.isDragSelect&&e<g&&(a-=b);0>a?this.x-=this.slideableWidth:a>=b&&(this.x+=this.slideableWidth)};h.previous=function(a,b){this.select(this.selectedIndex-1,a,b)};h.next=function(a,b){this.select(this.selectedIndex+1,a,b)};h.updateSelectedSlide=function(){var a=this.slides[this.selectedIndex];a&&(this.unselectSelectedSlide(),this.selectedSlide=a,a.select(),this.selectedCells=a.cells,
this.selectedElements=a.getCellElements(),this.selectedCell=a.cells[0],this.selectedElement=this.selectedElements[0])};h.unselectSelectedSlide=function(){this.selectedSlide&&this.selectedSlide.unselect()};h.selectCell=function(a,b,e){"number"==typeof a?a=this.cells[a]:("string"==typeof a&&(a=this.element.querySelector(a)),a=this.getCell(a));for(var g=0;a&&g<this.slides.length;g++)if(-1!=this.slides[g].cells.indexOf(a)){this.select(g,b,e);break}};h.getCell=function(a){for(var b=0;b<this.cells.length;b++){var e=
this.cells[b];if(e.element==a)return e}};h.getCells=function(a){a=d.makeArray(a);var b=[];a.forEach(function(a){(a=this.getCell(a))&&b.push(a)},this);return b};h.getCellElements=function(){return this.cells.map(function(a){return a.element})};h.getParentCell=function(a){var b=this.getCell(a);if(b)return b;a=d.getParent(a,".flickity-slider > *");return this.getCell(a)};h.getAdjacentCellElements=function(a,b){if(!a)return this.selectedSlide.getCellElements();b=void 0===b?this.selectedIndex:b;var e=
this.slides.length;if(1+2*a>=e)return this.getCellElements();for(var g=[],c=b-a;c<=b+a;c++){var m=this.options.wrapAround?d.modulo(c,e):c;(m=this.slides[m])&&(g=g.concat(m.getCellElements()))}return g};h.uiChange=function(){this.emitEvent("uiChange")};h.childUIPointerDown=function(a){this.emitEvent("childUIPointerDown",[a])};h.onresize=function(){this.watchCSS();this.resize()};d.debounceMethod(k,"onresize",150);h.resize=function(){this.isActive&&(this.getSize(),this.options.wrapAround&&(this.x=d.modulo(this.x,
this.slideableWidth)),this.positionCells(),this._getWrapShiftCells(),this.setGallerySize(),this.emitEvent("resize"),this.selectCell(this.selectedElements&&this.selectedElements[0],!1,!0))};h.watchCSS=function(){this.options.watchCSS&&(-1!=r(this.element,":after").content.indexOf("flickity")?this.activate():this.deactivate())};h.onkeydown=function(a){!this.options.accessibility||document.activeElement&&document.activeElement!=this.element||(37==a.keyCode?(a=this.options.rightToLeft?"next":"previous",
this.uiChange(),this[a]()):39==a.keyCode&&(a=this.options.rightToLeft?"previous":"next",this.uiChange(),this[a]()))};h.deactivate=function(){this.isActive&&(this.element.classList.remove("flickity-enabled"),this.element.classList.remove("flickity-rtl"),this.cells.forEach(function(a){a.destroy()}),this.unselectSelectedSlide(),this.element.removeChild(this.viewport),n(this.slider.children,this.element),this.options.accessibility&&(this.element.removeAttribute("tabIndex"),this.element.removeEventListener("keydown",
this)),this.isActive=!1,this.emitEvent("deactivate"))};h.destroy=function(){this.deactivate();b.removeEventListener("resize",this);this.emitEvent("destroy");l&&this.$element&&l.removeData(this.element,"flickity");delete this.element.flickityGUID;delete q[this.guid]};d.extend(h,g);k.data=function(a){return(a=(a=d.getQueryElement(a))&&a.flickityGUID)&&q[a]};d.htmlInit(k,"flickity");l&&l.bridget&&l.bridget("flickity",k);k.Cell=a;return k});
(function(b,c){"function"==typeof define&&define.amd?define("unipointer/unipointer",["ev-emitter/ev-emitter"],function(f){return c(b,f)}):"object"==typeof module&&module.exports?module.exports=c(b,require("ev-emitter")):b.Unipointer=c(b,b.EvEmitter)})(window,function(b,c){function f(){}var d=f.prototype=Object.create(c.prototype);d.bindStartEvent=function(a){this._bindStartEvent(a,!0)};d.unbindStartEvent=function(a){this._bindStartEvent(a,!1)};d._bindStartEvent=function(a,g){var e=void 0===g||g?"addEventListener":
"removeEventListener";if(b.navigator.pointerEnabled)a[e]("pointerdown",this);else if(b.navigator.msPointerEnabled)a[e]("MSPointerDown",this);else a[e]("mousedown",this),a[e]("touchstart",this)};d.handleEvent=function(a){var b="on"+a.type;if(this[b])this[b](a)};d.getTouch=function(a){for(var b=0;b<a.length;b++){var e=a[b];if(e.identifier==this.pointerIdentifier)return e}};d.onmousedown=function(a){var b=a.button;b&&0!==b&&1!==b||this._pointerDown(a,a)};d.ontouchstart=function(a){this._pointerDown(a,
a.changedTouches[0])};d.onMSPointerDown=d.onpointerdown=function(a){this._pointerDown(a,a)};d._pointerDown=function(a,b){this.isPointerDown||(this.isPointerDown=!0,this.pointerIdentifier=void 0!==b.pointerId?b.pointerId:b.identifier,this.pointerDown(a,b))};d.pointerDown=function(a,b){this._bindPostStartEvents(a);this.emitEvent("pointerDown",[a,b])};var a={mousedown:["mousemove","mouseup"],touchstart:["touchmove","touchend","touchcancel"],pointerdown:["pointermove","pointerup","pointercancel"],MSPointerDown:["MSPointerMove",
"MSPointerUp","MSPointerCancel"]};d._bindPostStartEvents=function(e){e&&(e=a[e.type],e.forEach(function(a){b.addEventListener(a,this)},this),this._boundPointerEvents=e)};d._unbindPostStartEvents=function(){this._boundPointerEvents&&(this._boundPointerEvents.forEach(function(a){b.removeEventListener(a,this)},this),delete this._boundPointerEvents)};d.onmousemove=function(a){this._pointerMove(a,a)};d.onMSPointerMove=d.onpointermove=function(a){a.pointerId==this.pointerIdentifier&&this._pointerMove(a,
a)};d.ontouchmove=function(a){var b=this.getTouch(a.changedTouches);b&&this._pointerMove(a,b)};d._pointerMove=function(a,b){this.pointerMove(a,b)};d.pointerMove=function(a,b){this.emitEvent("pointerMove",[a,b])};d.onmouseup=function(a){this._pointerUp(a,a)};d.onMSPointerUp=d.onpointerup=function(a){a.pointerId==this.pointerIdentifier&&this._pointerUp(a,a)};d.ontouchend=function(a){var b=this.getTouch(a.changedTouches);b&&this._pointerUp(a,b)};d._pointerUp=function(a,b){this._pointerDone();this.pointerUp(a,
b)};d.pointerUp=function(a,b){this.emitEvent("pointerUp",[a,b])};d._pointerDone=function(){this.isPointerDown=!1;delete this.pointerIdentifier;this._unbindPostStartEvents();this.pointerDone()};d.pointerDone=function(){};d.onMSPointerCancel=d.onpointercancel=function(a){a.pointerId==this.pointerIdentifier&&this._pointerCancel(a,a)};d.ontouchcancel=function(a){var b=this.getTouch(a.changedTouches);b&&this._pointerCancel(a,b)};d._pointerCancel=function(a,b){this._pointerDone();this.pointerCancel(a,b)};
d.pointerCancel=function(a,b){this.emitEvent("pointerCancel",[a,b])};f.getPointerPoint=function(a){return{x:a.pageX,y:a.pageY}};return f});
(function(b,c){"function"==typeof define&&define.amd?define("unidragger/unidragger",["unipointer/unipointer"],function(f){return c(b,f)}):"object"==typeof module&&module.exports?module.exports=c(b,require("unipointer")):b.Unidragger=c(b,b.Unipointer)})(window,function(b,c){function f(){}function d(){}var a=d.prototype=Object.create(c.prototype);a.bindHandles=function(){this._bindHandles(!0)};a.unbindHandles=function(){this._bindHandles(!1)};var e=b.navigator;a._bindHandles=function(a){a=void 0===
a?!0:!!a;var b;b=e.pointerEnabled?function(b){b.style.touchAction=a?"none":""}:e.msPointerEnabled?function(b){b.style.msTouchAction=a?"none":""}:f;for(var c=a?"addEventListener":"removeEventListener",g=0;g<this.handles.length;g++){var d=this.handles[g];this._bindStartEvent(d,a);b(d);d[c]("click",this)}};a.pointerDown=function(a,b){if("INPUT"==a.target.nodeName&&"range"==a.target.type)this.isPointerDown=!1,delete this.pointerIdentifier;else{this._dragPointerDown(a,b);var c=document.activeElement;c&&
c.blur&&c.blur();this._bindPostStartEvents(a);this.emitEvent("pointerDown",[a,b])}};a._dragPointerDown=function(a,b){this.pointerDownPoint=c.getPointerPoint(b);this.canPreventDefaultOnPointerDown(a,b)&&a.preventDefault()};a.canPreventDefaultOnPointerDown=function(a){return"SELECT"!=a.target.nodeName};a.pointerMove=function(a,b){var c=this._dragPointerMove(a,b);this.emitEvent("pointerMove",[a,b,c]);this._dragMove(a,b,c)};a._dragPointerMove=function(a,b){var e=c.getPointerPoint(b),e={x:e.x-this.pointerDownPoint.x,
y:e.y-this.pointerDownPoint.y};!this.isDragging&&this.hasDragStarted(e)&&this._dragStart(a,b);return e};a.hasDragStarted=function(a){return 3<Math.abs(a.x)||3<Math.abs(a.y)};a.pointerUp=function(a,b){this.emitEvent("pointerUp",[a,b]);this._dragPointerUp(a,b)};a._dragPointerUp=function(a,b){this.isDragging?this._dragEnd(a,b):this._staticClick(a,b)};a._dragStart=function(a,b){this.isDragging=!0;this.dragStartPoint=c.getPointerPoint(b);this.isPreventingClicks=!0;this.dragStart(a,b)};a.dragStart=function(a,
b){this.emitEvent("dragStart",[a,b])};a._dragMove=function(a,b,c){this.isDragging&&this.dragMove(a,b,c)};a.dragMove=function(a,b,c){a.preventDefault();this.emitEvent("dragMove",[a,b,c])};a._dragEnd=function(a,b){this.isDragging=!1;setTimeout(function(){delete this.isPreventingClicks}.bind(this));this.dragEnd(a,b)};a.dragEnd=function(a,b){this.emitEvent("dragEnd",[a,b])};a.onclick=function(a){this.isPreventingClicks&&a.preventDefault()};a._staticClick=function(a,b){if(!this.isIgnoringMouseUp||"mouseup"!=
a.type){var c=a.target.nodeName;"INPUT"!=c&&"TEXTAREA"!=c||a.target.focus();this.staticClick(a,b);"mouseup"!=a.type&&(this.isIgnoringMouseUp=!0,setTimeout(function(){delete this.isIgnoringMouseUp}.bind(this),400))}};a.staticClick=function(a,b){this.emitEvent("staticClick",[a,b])};d.getPointerPoint=c.getPointerPoint;return d});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/drag",["./flickity","unidragger/unidragger","fizzy-ui-utils/utils"],function(f,d,a){return c(b,f,d,a)}):"object"==typeof module&&module.exports?module.exports=c(b,require("./flickity"),require("unidragger"),require("fizzy-ui-utils")):b.Flickity=c(b,b.Flickity,b.Unidragger,b.fizzyUIUtils)})(window,function(b,c,f,d){d.extend(c.defaults,{draggable:!0,dragThreshold:3});c.createMethods.push("_createDrag");var a=c.prototype;d.extend(a,
f.prototype);var e="createTouch"in document,g=!1;a._createDrag=function(){this.on("activate",this.bindDrag);this.on("uiChange",this._uiChangeDrag);this.on("childUIPointerDown",this._childUIPointerDownDrag);this.on("deactivate",this.unbindDrag);e&&!g&&(b.addEventListener("touchmove",function(){}),g=!0)};a.bindDrag=function(){this.options.draggable&&!this.isDragBound&&(this.element.classList.add("is-draggable"),this.handles=[this.viewport],this.bindHandles(),this.isDragBound=!0)};a.unbindDrag=function(){this.isDragBound&&
(this.element.classList.remove("is-draggable"),this.unbindHandles(),delete this.isDragBound)};a._uiChangeDrag=function(){delete this.isFreeScrolling};a._childUIPointerDownDrag=function(a){a.preventDefault();this.pointerDownFocus(a)};var n={TEXTAREA:!0,INPUT:!0,OPTION:!0},k={radio:!0,checkbox:!0,button:!0,submit:!0,image:!0,file:!0};a.pointerDown=function(a,c){if(n[a.target.nodeName]&&!k[a.target.type])this.isPointerDown=!1,delete this.pointerIdentifier;else{this._dragPointerDown(a,c);var e=document.activeElement;
e&&e.blur&&e!=this.element&&e!=document.body&&e.blur();this.pointerDownFocus(a);this.dragX=this.x;this.viewport.classList.add("is-pointer-down");this._bindPostStartEvents(a);this.pointerDownScroll={x:b.pageXOffset,y:b.pageYOffset};b.addEventListener("scroll",this);this.dispatchEvent("pointerDown",a,[c])}};var l={touchstart:!0,MSPointerDown:!0},r={INPUT:!0,SELECT:!0};a.pointerDownFocus=function(a){!this.options.accessibility||l[a.type]||r[a.target.nodeName]||(a=b.pageYOffset,this.element.focus(),b.pageYOffset!=
a&&b.scrollTo(b.pageXOffset,a))};a.canPreventDefaultOnPointerDown=function(a){var b=a.target.nodeName;return"touchstart"!=a.type&&"SELECT"!=b};a.hasDragStarted=function(a){return Math.abs(a.x)>this.options.dragThreshold};a.pointerUp=function(a,b){delete this.isTouchScrolling;this.viewport.classList.remove("is-pointer-down");this.dispatchEvent("pointerUp",a,[b]);this._dragPointerUp(a,b)};a.pointerDone=function(){b.removeEventListener("scroll",this);delete this.pointerDownScroll};a.dragStart=function(a,
c){this.dragStartPosition=this.x;this.startAnimation();b.removeEventListener("scroll",this);this.dispatchEvent("dragStart",a,[c])};a.pointerMove=function(a,b){var c=this._dragPointerMove(a,b);this.dispatchEvent("pointerMove",a,[b,c]);this._dragMove(a,b,c)};a.dragMove=function(a,b,c){a.preventDefault();this.previousDragX=this.dragX;var e=this.dragStartPosition+c.x*(this.options.rightToLeft?-1:1);if(!this.options.wrapAround&&this.slides.length)var d=Math.max(-this.slides[0].target,this.dragStartPosition),
e=e>d?.5*(e+d):e,d=Math.min(-this.getLastSlide().target,this.dragStartPosition),e=e<d?.5*(e+d):e;this.dragX=e;this.dragMoveTime=new Date;this.dispatchEvent("dragMove",a,[b,c])};a.dragEnd=function(a,b){this.options.freeScroll&&(this.isFreeScrolling=!0);var c=this.dragEndRestingSelect();if(this.options.freeScroll&&!this.options.wrapAround){var e=this.getRestingPosition();this.isFreeScrolling=-e>this.slides[0].target&&-e<this.getLastSlide().target}else this.options.freeScroll||c!=this.selectedIndex||
(c+=this.dragEndBoostSelect());delete this.previousDragX;this.isDragSelect=this.options.wrapAround;this.select(c);delete this.isDragSelect;this.dispatchEvent("dragEnd",a,[b])};a.dragEndRestingSelect=function(){var a=this.getRestingPosition(),b=Math.abs(this.getSlideDistance(-a,this.selectedIndex)),c=this._getClosestResting(a,b,1),a=this._getClosestResting(a,b,-1);return c.distance<a.distance?c.index:a.index};a._getClosestResting=function(a,b,c){for(var e=this.selectedIndex,d=Infinity,g=this.options.contain&&
!this.options.wrapAround?function(a,b){return a<=b}:function(a,b){return a<b};g(b,d);){e+=c;d=b;b=this.getSlideDistance(-a,e);if(null===b)break;b=Math.abs(b)}return{distance:d,index:e-c}};a.getSlideDistance=function(a,b){var c=this.slides.length,e=this.options.wrapAround&&1<c,g=e?d.modulo(b,c):b;return(g=this.slides[g])?a-(g.target+(e?this.slideableWidth*Math.floor(b/c):0)):null};a.dragEndBoostSelect=function(){if(void 0===this.previousDragX||!this.dragMoveTime||100<new Date-this.dragMoveTime)return 0;
var a=this.getSlideDistance(-this.dragX,this.selectedIndex),b=this.previousDragX-this.dragX;return 0<a&&0<b?1:0>a&&0>b?-1:0};a.staticClick=function(a,b){var c=this.getParentCell(a.target),e=c&&c.element,c=c&&this.cells.indexOf(c);this.dispatchEvent("staticClick",a,[b,e,c])};a.onscroll=function(){var a=this.pointerDownScroll.y-b.pageYOffset;(3<Math.abs(this.pointerDownScroll.x-b.pageXOffset)||3<Math.abs(a))&&this._pointerDone()};return c});
(function(b,c){"function"==typeof define&&define.amd?define("tap-listener/tap-listener",["unipointer/unipointer"],function(f){return c(b,f)}):"object"==typeof module&&module.exports?module.exports=c(b,require("unipointer")):b.TapListener=c(b,b.Unipointer)})(window,function(b,c){function f(a){this.bindTap(a)}var d=f.prototype=Object.create(c.prototype);d.bindTap=function(a){a&&(this.unbindTap(),this.tapElement=a,this._bindStartEvent(a,!0))};d.unbindTap=function(){this.tapElement&&(this._bindStartEvent(this.tapElement,
!0),delete this.tapElement)};d.pointerUp=function(a,e){if(!this.isIgnoringMouseUp||"mouseup"!=a.type){var d=c.getPointerPoint(e),f=this.tapElement.getBoundingClientRect(),k=b.pageXOffset,l=b.pageYOffset;d.x>=f.left+k&&d.x<=f.right+k&&d.y>=f.top+l&&d.y<=f.bottom+l&&this.emitEvent("tap",[a,e]);if("mouseup"!=a.type){this.isIgnoringMouseUp=!0;var r=this;setTimeout(function(){delete r.isIgnoringMouseUp},400)}}};d.destroy=function(){this.pointerDone();this.unbindTap()};return f});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/prev-next-button",["./flickity","tap-listener/tap-listener","fizzy-ui-utils/utils"],function(f,d,a){return c(b,f,d,a)}):"object"==typeof module&&module.exports?module.exports=c(b,require("./flickity"),require("tap-listener"),require("fizzy-ui-utils")):c(b,b.Flickity,b.TapListener,b.fizzyUIUtils)})(window,function(b,c,f,d){function a(a,b){this.direction=a;this.parent=b;this._create()}a.prototype=new f;a.prototype._create=function(){this.isEnabled=
!0;this.isPrevious=-1==this.direction;this.isLeft=this.direction==(this.parent.options.rightToLeft?1:-1);var a=this.element=document.createElement("button");a.className="flickity-prev-next-button";a.className+=this.isPrevious?" previous":" next";a.setAttribute("type","button");this.disable();a.setAttribute("aria-label",this.isPrevious?"previous":"next");var b=this.createSVG();a.appendChild(b);this.on("tap",this.onTap);this.parent.on("select",this.update.bind(this));this.on("pointerDown",this.parent.childUIPointerDown.bind(this.parent))};
a.prototype.activate=function(){this.bindTap(this.element);this.element.addEventListener("click",this);this.parent.element.appendChild(this.element)};a.prototype.deactivate=function(){this.parent.element.removeChild(this.element);f.prototype.destroy.call(this);this.element.removeEventListener("click",this)};a.prototype.createSVG=function(){var a=document.createElementNS("http://www.w3.org/2000/svg","svg");a.setAttribute("viewBox","0 0 100 100");var b=document.createElementNS("http://www.w3.org/2000/svg",
"path"),c;c=this.parent.options.arrowShape;c="string"==typeof c?c:"M "+c.x0+",50 L "+c.x1+","+(c.y1+50)+" L "+c.x2+","+(c.y2+50)+" L "+c.x3+",50  L "+c.x2+","+(50-c.y2)+" L "+c.x1+","+(50-c.y1)+" Z";b.setAttribute("d",c);b.setAttribute("class","arrow");this.isLeft||b.setAttribute("transform","translate(100, 100) rotate(180) ");a.appendChild(b);return a};a.prototype.onTap=function(){this.isEnabled&&(this.parent.uiChange(),this.parent[this.isPrevious?"previous":"next"]())};a.prototype.handleEvent=d.handleEvent;
a.prototype.onclick=function(){var a=document.activeElement;if(a&&a==this.element)this.onTap()};a.prototype.enable=function(){this.isEnabled||(this.element.disabled=!1,this.isEnabled=!0)};a.prototype.disable=function(){this.isEnabled&&(this.element.disabled=!0,this.isEnabled=!1)};a.prototype.update=function(){var a=this.parent.slides;this.parent.options.wrapAround&&1<a.length?this.enable():(a=a.length?a.length-1:0,this[this.parent.selectedIndex==(this.isPrevious?0:a)?"disable":"enable"]())};a.prototype.destroy=
function(){this.deactivate()};d.extend(c.defaults,{prevNextButtons:!0,arrowShape:{x0:10,x1:60,y1:50,x2:70,y2:40,x3:30}});c.createMethods.push("_createPrevNextButtons");b=c.prototype;b._createPrevNextButtons=function(){this.options.prevNextButtons&&(this.prevButton=new a(-1,this),this.nextButton=new a(1,this),this.on("activate",this.activatePrevNextButtons))};b.activatePrevNextButtons=function(){this.prevButton.activate();this.nextButton.activate();this.on("deactivate",this.deactivatePrevNextButtons)};
b.deactivatePrevNextButtons=function(){this.prevButton.deactivate();this.nextButton.deactivate();this.off("deactivate",this.deactivatePrevNextButtons)};c.PrevNextButton=a;return c});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/page-dots",["./flickity","tap-listener/tap-listener","fizzy-ui-utils/utils"],function(f,d,a){return c(b,f,d,a)}):"object"==typeof module&&module.exports?module.exports=c(b,require("./flickity"),require("tap-listener"),require("fizzy-ui-utils")):c(b,b.Flickity,b.TapListener,b.fizzyUIUtils)})(window,function(b,c,f,d){function a(a){this.parent=a;this._create()}a.prototype=new f;a.prototype._create=function(){this.holder=document.createElement("ol");
this.holder.className="flickity-page-dots";this.dots=[];this.on("tap",this.onTap);this.on("pointerDown",this.parent.childUIPointerDown.bind(this.parent))};a.prototype.activate=function(){this.setDots();this.bindTap(this.holder);this.parent.element.appendChild(this.holder)};a.prototype.deactivate=function(){this.parent.element.removeChild(this.holder);f.prototype.destroy.call(this)};a.prototype.setDots=function(){var a=this.parent.slides.length-this.dots.length;0<a?this.addDots(a):0>a&&this.removeDots(-a)};
a.prototype.addDots=function(a){for(var b=document.createDocumentFragment(),c=[];a;){var e=document.createElement("li");e.className="dot";b.appendChild(e);c.push(e);a--}this.holder.appendChild(b);this.dots=this.dots.concat(c)};a.prototype.removeDots=function(a){this.dots.splice(this.dots.length-a,a).forEach(function(a){this.holder.removeChild(a)},this)};a.prototype.updateSelected=function(){this.selectedDot&&(this.selectedDot.className="dot");this.dots.length&&(this.selectedDot=this.dots[this.parent.selectedIndex],
this.selectedDot.className="dot is-selected")};a.prototype.onTap=function(a){a=a.target;"LI"==a.nodeName&&(this.parent.uiChange(),a=this.dots.indexOf(a),this.parent.select(a))};a.prototype.destroy=function(){this.deactivate()};c.PageDots=a;d.extend(c.defaults,{pageDots:!0});c.createMethods.push("_createPageDots");b=c.prototype;b._createPageDots=function(){this.options.pageDots&&(this.pageDots=new a(this),this.on("activate",this.activatePageDots),this.on("select",this.updateSelectedPageDots),this.on("cellChange",
this.updatePageDots),this.on("resize",this.updatePageDots),this.on("deactivate",this.deactivatePageDots))};b.activatePageDots=function(){this.pageDots.activate()};b.updateSelectedPageDots=function(){this.pageDots.updateSelected()};b.updatePageDots=function(){this.pageDots.setDots()};b.deactivatePageDots=function(){this.pageDots.deactivate()};c.PageDots=a;return c});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/player",["ev-emitter/ev-emitter","fizzy-ui-utils/utils","./flickity"],function(b,d,a){return c(b,d,a)}):"object"==typeof module&&module.exports?module.exports=c(require("ev-emitter"),require("fizzy-ui-utils"),require("./flickity")):c(b.EvEmitter,b.fizzyUIUtils,b.Flickity)})(window,function(b,c,f){function d(a){this.parent=a;this.state="stopped";e&&(this.onVisibilityChange=function(){this.visibilityChange()}.bind(this),this.onVisibilityPlay=
function(){this.visibilityPlay()}.bind(this))}var a,e;"hidden"in document?(a="hidden",e="visibilitychange"):"webkitHidden"in document&&(a="webkitHidden",e="webkitvisibilitychange");d.prototype=Object.create(b.prototype);d.prototype.play=function(){if("playing"!=this.state){var b=document[a];e&&b?document.addEventListener(e,this.onVisibilityPlay):(this.state="playing",e&&document.addEventListener(e,this.onVisibilityChange),this.tick())}};d.prototype.tick=function(){if("playing"==this.state){var a=
this.parent.options.autoPlay,a="number"==typeof a?a:3E3,b=this;this.clear();this.timeout=setTimeout(function(){b.parent.next(!0);b.tick()},a)}};d.prototype.stop=function(){this.state="stopped";this.clear();e&&document.removeEventListener(e,this.onVisibilityChange)};d.prototype.clear=function(){clearTimeout(this.timeout)};d.prototype.pause=function(){"playing"==this.state&&(this.state="paused",this.clear())};d.prototype.unpause=function(){"paused"==this.state&&this.play()};d.prototype.visibilityChange=
function(){this[document[a]?"pause":"unpause"]()};d.prototype.visibilityPlay=function(){this.play();document.removeEventListener(e,this.onVisibilityPlay)};c.extend(f.defaults,{pauseAutoPlayOnHover:!0});f.createMethods.push("_createPlayer");b=f.prototype;b._createPlayer=function(){this.player=new d(this);this.on("activate",this.activatePlayer);this.on("uiChange",this.stopPlayer);this.on("pointerDown",this.stopPlayer);this.on("deactivate",this.deactivatePlayer)};b.activatePlayer=function(){this.options.autoPlay&&
(this.player.play(),this.element.addEventListener("mouseenter",this))};b.playPlayer=function(){this.player.play()};b.stopPlayer=function(){this.player.stop()};b.pausePlayer=function(){this.player.pause()};b.unpausePlayer=function(){this.player.unpause()};b.deactivatePlayer=function(){this.player.stop();this.element.removeEventListener("mouseenter",this)};b.onmouseenter=function(){this.options.pauseAutoPlayOnHover&&(this.player.pause(),this.element.addEventListener("mouseleave",this))};b.onmouseleave=
function(){this.player.unpause();this.element.removeEventListener("mouseleave",this)};f.Player=d;return f});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/add-remove-cell",["./flickity","fizzy-ui-utils/utils"],function(f,d){return c(b,f,d)}):"object"==typeof module&&module.exports?module.exports=c(b,require("./flickity"),require("fizzy-ui-utils")):c(b,b.Flickity,b.fizzyUIUtils)})(window,function(b,c,f){function d(a){var b=document.createDocumentFragment();a.forEach(function(a){b.appendChild(a.element)});return b}b=c.prototype;b.insert=function(a,b){var c=this._makeCells(a);if(c&&
c.length){var e=this.cells.length;b=void 0===b?e:b;var f=d(c),l=b==e;l?this.slider.appendChild(f):this.slider.insertBefore(f,this.cells[b].element);0===b?this.cells=c.concat(this.cells):l?this.cells=this.cells.concat(c):(e=this.cells.splice(b,e-b),this.cells=this.cells.concat(c).concat(e));this._sizeCells(c);this._cellAddedRemoved(b,b>this.selectedIndex?0:c.length)}};b.append=function(a){this.insert(a,this.cells.length)};b.prepend=function(a){this.insert(a,0)};b.remove=function(a){a=this.getCells(a);
var b=0,c=a.length,d,k;for(d=0;d<c;d++)k=a[d],k=this.cells.indexOf(k)<this.selectedIndex,b-=k?1:0;for(d=0;d<c;d++)k=a[d],k.remove(),f.removeFrom(this.cells,k);a.length&&this._cellAddedRemoved(0,b)};b._cellAddedRemoved=function(a,b){b=b||0;this.selectedIndex+=b;this.selectedIndex=Math.max(0,Math.min(this.slides.length-1,this.selectedIndex));this.cellChange(a,!0);this.emitEvent("cellAddedRemoved",[a,b])};b.cellSizeChange=function(a){if(a=this.getCell(a))a.getSize(),a=this.cells.indexOf(a),this.cellChange(a)};
b.cellChange=function(a,b){var c=this.slideableWidth;this._positionCells(a);this._getWrapShiftCells();this.setGallerySize();this.emitEvent("cellChange",[a]);this.options.freeScroll?(this.x+=(c-this.slideableWidth)*this.cellAlign,this.positionSlider()):(b&&this.positionSliderAtSelected(),this.select(this.selectedIndex))};return c});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/lazyload",["./flickity","fizzy-ui-utils/utils"],function(f,d){return c(b,f,d)}):"object"==typeof module&&module.exports?module.exports=c(b,require("./flickity"),require("fizzy-ui-utils")):c(b,b.Flickity,b.fizzyUIUtils)})(window,function(b,c,f){function d(a,b){this.img=a;this.flickity=b;this.load()}c.createMethods.push("_createLazyload");b=c.prototype;b._createLazyload=function(){this.on("select",this.lazyLoad)};b.lazyLoad=function(){var a=
this.options.lazyLoad;if(a){var b=[];this.getAdjacentCellElements("number"==typeof a?a:0).forEach(function(a){"IMG"==a.nodeName&&a.getAttribute("data-flickity-lazyload")?a=[a]:(a=a.querySelectorAll("img[data-flickity-lazyload]"),a=f.makeArray(a));b=b.concat(a)});b.forEach(function(a){new d(a,this)},this)}};d.prototype.handleEvent=f.handleEvent;d.prototype.load=function(){this.img.addEventListener("load",this);this.img.addEventListener("error",this);this.img.src=this.img.getAttribute("data-flickity-lazyload");
this.img.removeAttribute("data-flickity-lazyload")};d.prototype.onload=function(a){this.complete(a,"flickity-lazyloaded")};d.prototype.onerror=function(a){this.complete(a,"flickity-lazyerror")};d.prototype.complete=function(a,b){this.img.removeEventListener("load",this);this.img.removeEventListener("error",this);var c=this.flickity.getParentCell(this.img),c=c&&c.element;this.flickity.cellSizeChange(c);this.img.classList.add(b);this.flickity.dispatchEvent("lazyLoad",a,c)};c.LazyLoader=d;return c});
(function(b,c){"function"==typeof define&&define.amd?define("flickity/js/index","./flickity ./drag ./prev-next-button ./page-dots ./player ./add-remove-cell ./lazyload".split(" "),c):"object"==typeof module&&module.exports&&(module.exports=c(require("./flickity"),require("./drag"),require("./prev-next-button"),require("./page-dots"),require("./player"),require("./add-remove-cell"),require("./lazyload")))})(window,function(b){return b});
(function(b,c){"function"==typeof define&&define.amd?define("flickity-as-nav-for/as-nav-for",["flickity/js/index","fizzy-ui-utils/utils"],c):"object"==typeof module&&module.exports?module.exports=c(require("flickity"),require("fizzy-ui-utils")):b.Flickity=c(b.Flickity,b.fizzyUIUtils)})(window,function(b,c){b.createMethods.push("_createAsNavFor");var f=b.prototype;f._createAsNavFor=function(){this.on("activate",this.activateAsNavFor);this.on("deactivate",this.deactivateAsNavFor);this.on("destroy",
this.destroyAsNavFor);var b=this.options.asNavFor;if(b){var a=this;setTimeout(function(){a.setNavCompanion(b)})}};f.setNavCompanion=function(d){d=c.getQueryElement(d);if((d=b.data(d))&&d!=this){this.navCompanion=d;var a=this;this.onNavCompanionSelect=function(){a.navCompanionSelect()};d.on("select",this.onNavCompanionSelect);this.on("staticClick",this.onNavStaticClick);this.navCompanionSelect(!0)}};f.navCompanionSelect=function(b){if(this.navCompanion){var a=this.navCompanion.cells.indexOf(this.navCompanion.selectedCells[0]),
c=a+this.navCompanion.selectedCells.length-1,d=Math.floor((c-a)*this.navCompanion.cellAlign+a);this.selectCell(d,!1,b);this.removeNavSelectedElements();d>=this.cells.length||(this.navSelectedElements=this.cells.slice(a,c+1).map(function(a){return a.element}),this.changeNavSelectedClass("add"))}};f.changeNavSelectedClass=function(b){this.navSelectedElements.forEach(function(a){a.classList[b]("is-nav-selected")})};f.activateAsNavFor=function(){this.navCompanionSelect(!0)};f.removeNavSelectedElements=
function(){this.navSelectedElements&&(this.changeNavSelectedClass("remove"),delete this.navSelectedElements)};f.onNavStaticClick=function(b,a,c,f){"number"==typeof f&&this.navCompanion.selectCell(f)};f.deactivateAsNavFor=function(){this.removeNavSelectedElements()};f.destroyAsNavFor=function(){this.navCompanion&&(this.navCompanion.off("select",this.onNavCompanionSelect),this.off("staticClick",this.onNavStaticClick),delete this.navCompanion)};return b});
(function(b,c){"function"==typeof define&&define.amd?define("imagesloaded/imagesloaded",["ev-emitter/ev-emitter"],function(f){return c(b,f)}):"object"==typeof module&&module.exports?module.exports=c(b,require("ev-emitter")):b.imagesLoaded=c(b,b.EvEmitter)})(window,function(b,c){function f(a,b){for(var c in b)a[c]=b[c];return a}function d(a){var b=[];if(Array.isArray(a))b=a;else if("number"==typeof a.length)for(var c=0;c<a.length;c++)b.push(a[c]);else b.push(a);return b}function a(b,c,e){if(!(this instanceof
a))return new a(b,c,e);"string"==typeof b&&(b=document.querySelectorAll(b));this.elements=d(b);this.options=f({},this.options);"function"==typeof c?e=c:f(this.options,c);if(e)this.on("always",e);this.getImages();n&&(this.jqDeferred=new n.Deferred);setTimeout(function(){this.check()}.bind(this))}function e(a){this.img=a}function g(a,b){this.url=a;this.element=b;this.img=new Image}var n=b.jQuery,k=b.console;a.prototype=Object.create(c.prototype);a.prototype.options={};a.prototype.getImages=function(){this.images=
[];this.elements.forEach(this.addElementImages,this)};a.prototype.addElementImages=function(a){"IMG"==a.nodeName&&this.addImage(a);!0===this.options.background&&this.addElementBackgroundImages(a);var b=a.nodeType;if(b&&l[b]){for(var c=a.querySelectorAll("img"),b=0;b<c.length;b++)this.addImage(c[b]);if("string"==typeof this.options.background)for(a=a.querySelectorAll(this.options.background),b=0;b<a.length;b++)this.addElementBackgroundImages(a[b])}};var l={1:!0,9:!0,11:!0};a.prototype.addElementBackgroundImages=
function(a){var b=getComputedStyle(a);if(b)for(var c=/url\((['"])?(.*?)\1\)/gi,d=c.exec(b.backgroundImage);null!==d;)(d=d&&d[2])&&this.addBackground(d,a),d=c.exec(b.backgroundImage)};a.prototype.addImage=function(a){a=new e(a);this.images.push(a)};a.prototype.addBackground=function(a,b){var c=new g(a,b);this.images.push(c)};a.prototype.check=function(){function a(a,c,d){setTimeout(function(){b.progress(a,c,d)})}var b=this;this.progressedCount=0;this.hasAnyBroken=!1;this.images.length?this.images.forEach(function(b){b.once("progress",
a);b.check()}):this.complete()};a.prototype.progress=function(a,b,c){this.progressedCount++;this.hasAnyBroken=this.hasAnyBroken||!a.isLoaded;this.emitEvent("progress",[this,a,b]);this.jqDeferred&&this.jqDeferred.notify&&this.jqDeferred.notify(this,a);this.progressedCount==this.images.length&&this.complete();this.options.debug&&k&&k.log("progress: "+c,a,b)};a.prototype.complete=function(){var a=this.hasAnyBroken?"fail":"done";this.isComplete=!0;this.emitEvent(a,[this]);this.emitEvent("always",[this]);
if(this.jqDeferred)this.jqDeferred[this.hasAnyBroken?"reject":"resolve"](this)};e.prototype=Object.create(c.prototype);e.prototype.check=function(){this.getIsImageComplete()?this.confirm(0!==this.img.naturalWidth,"naturalWidth"):(this.proxyImage=new Image,this.proxyImage.addEventListener("load",this),this.proxyImage.addEventListener("error",this),this.img.addEventListener("load",this),this.img.addEventListener("error",this),this.proxyImage.src=this.img.src)};e.prototype.getIsImageComplete=function(){return this.img.complete&&
void 0!==this.img.naturalWidth};e.prototype.confirm=function(a,b){this.isLoaded=a;this.emitEvent("progress",[this,this.img,b])};e.prototype.handleEvent=function(a){var b="on"+a.type;if(this[b])this[b](a)};e.prototype.onload=function(){this.confirm(!0,"onload");this.unbindEvents()};e.prototype.onerror=function(){this.confirm(!1,"onerror");this.unbindEvents()};e.prototype.unbindEvents=function(){this.proxyImage.removeEventListener("load",this);this.proxyImage.removeEventListener("error",this);this.img.removeEventListener("load",
this);this.img.removeEventListener("error",this)};g.prototype=Object.create(e.prototype);g.prototype.check=function(){this.img.addEventListener("load",this);this.img.addEventListener("error",this);this.img.src=this.url;this.getIsImageComplete()&&(this.confirm(0!==this.img.naturalWidth,"naturalWidth"),this.unbindEvents())};g.prototype.unbindEvents=function(){this.img.removeEventListener("load",this);this.img.removeEventListener("error",this)};g.prototype.confirm=function(a,b){this.isLoaded=a;this.emitEvent("progress",
[this,this.element,b])};a.makeJQueryPlugin=function(c){if(c=c||b.jQuery)n=c,n.fn.imagesLoaded=function(b,c){return(new a(this,b,c)).jqDeferred.promise(n(this))}};a.makeJQueryPlugin();return a});
(function(b,c){"function"==typeof define&&define.amd?define(["flickity/js/index","imagesloaded/imagesloaded"],function(f,d){return c(b,f,d)}):"object"==typeof module&&module.exports?module.exports=c(b,require("flickity"),require("imagesloaded")):b.Flickity=c(b,b.Flickity,b.imagesLoaded)})(window,function(b,c,f){c.createMethods.push("_createImagesLoaded");b=c.prototype;b._createImagesLoaded=function(){this.on("activate",this.imagesLoaded)};b.imagesLoaded=function(){if(this.options.imagesLoaded){var b=
this;f(this.slider).on("progress",function(a,c){var d=b.getParentCell(c.img);b.cellSizeChange(d&&d.element);b.options.freeScroll||b.positionSliderAtSelected()})}};return c});